name: "robot_2_move_mobile_2"
robot:
  class:
    class_path: "my_robot.test_robot"
    class_name: "TestRobot"
  args: null
run:
  function:
    function_path: "utils.task_functions"
    function_name: "move_mobile_to"
  args: 
    target: [0.35, 0.35, 0., 0., 0., -1.]
success:
  function:
    function_path: "utils.task_functions"
    function_name: "success"
  args:  
    threshold: 0.8
fail:
  function:
    function_path: "utils.task_functions"
    function_name: "success"
  args:  
    threshold: 0.1
