name: "robot_2_model_infer"
robot:
  class:
    class_path: "my_robot.test_robot_2"
    class_name: "TestRobot"
  args: null
run:
  function:
    function_path: "utils.task_functions"
    function_name: "infer_once"
  args: null
success:
  function:
    function_path: "utils.task_functions"
    function_name: "success"
  args: 
    threshold: 0.8
extras:
  model:
    class:
      class_path: "policy.test_policy.inference_model"
      class_name: "TestModel"
    args: 
      model_path: "model/path/"
      task_name: "test"
  release: true
fail:
  function:
    function_path: "utils.task_functions"
    function_name: "success"
  args:  
    threshold: 0.5

    